language: node_js
node_js:
  - 0.10
install:
  - npm install -g bower
  - bower install
script: npm run-script build
after_script:
  - mkdir -p deploy/populations
  - cp -r public/* deploy/populations/
after_success: if [ "$TRAVIS_BRANCH" == "production" ]; then bundle install --without dev; bundle exec s3_website push --site deploy --headless; fi
env:
  global:
  - secure: Qh6OyqAp+5jfJp/XGOtprYUrrnzCYSOqEGpRYAUBU6NmPpzA4uK6gILhQNcqmID5WC4B80k24gPAXhMUzeSlJ8otz1zavUwCIVVpGO3CfUEstDE1XuY9XP9h5hvUpoki4odDjjV2xyMs7SwPkPdH51LXQ8yyM08UGXuRsi3KhZ4=
  - secure: OwPaznU8bpE9yEddaoewNqTg3ZEz0Cz//NyNM8l0R807/k6w+QFfKLJ1YNjfK4yH0dfRdsl3W3+dWknZK1qbUVyc05K2ENc1J14nXSHNzw+kl5QuT2nZUDK2JF/78gK61qZA64pjUwLlK++vCEl1Lkv6nOUTYJMd5fJkkzQYgPo=
