language: node_js
node_js:
- 0.10
install:
- npm install -g bower
- npm install -g coffee-script
- npm install
- bower install
before_script:
- node_modules/.bin/brunch build
- cp -r public public-test
- node_modules/.bin/brunch build -P
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
script: node_modules/.bin/karma start test/karma.travis.conf.js
deploy:
  provider: s3
  access_key_id:
    secure: X48QoG+ZgSck1n3+VSAR/lzKF65cxPEdbbp8TcKAHaBDfRh5twSowbE0QE8l9yE4UbRSkmtbSCmsGkxsi6+AX4UZ3FkHR9Ke93ZHua1ncdfSOS+BMtfUl7/Q+Yhp8619G6VLGYDFQEmip89pNi+F5aFud9X9+qObWFJC1haVXB8=
  secret_access_key:
    secure: USiMwhfwJO2tEbQODWBUqjv5jwEfSFxn6v0KcaPdxNVLCDrXPFvmIBgP7F90lr5ulSMwM2d8deb2EMHkh7fCK2ABK+Qcvabez1VAjIdnKy7/1GROofxeeMBivosj8YEz+X9SJmdw7tJ4hAbkdcdIB0n9kW5uSGUVO0jl39zsknY=
  bucket: models-resources
  local-dir: public
  upload-dir: populations
  skip_cleanup: true
  on:
    repo: concord-consortium/populations.js
    branch: production
