// Generated by CoffeeScript 1.6.3
(function() {
  var Environment, Rule, env;

  Environment = require('models/environment');

  Rule = require('models/rule');

  env = new Environment({
    columns: 50,
    rows: 50,
    imgPath: "images/environments/green2.png",
    barriers: [],
    wrapEastWest: false,
    wrapNorthSouth: false
  });

  require.register("environments/open", function(exports, require, module) {
    return module.exports = env;
  });

}).call(this);
