// Generated by CoffeeScript 1.6.3
(function() {
  var Environment, Rule, env;

  Environment = require('models/environment');

  Rule = require('models/rule');

  env = new Environment({
    columns: 45,
    rows: 45,
    imgPath: "images/environments/snow.png",
    wrapEastWest: false,
    wrapNorthSouth: false
  });

  require.register("environments/snow", function(exports, require, module) {
    return module.exports = env;
  });

}).call(this);
