// Generated by CoffeeScript 1.6.3
(function() {
  require.register("species/plus-one", function(exports, require, module) {
    var Inanimate, Species;
    Species = require('models/species');
    Inanimate = require('models/inanimate');
    return module.exports = new Species({
      speciesName: "plus one",
      agentClass: Inanimate,
      defs: {},
      traits: [],
      imageRules: [
        {
          name: 'plus one',
          contexts: ['environment'],
          rules: [
            {
              image: {
                path: "images/agents/hawks/hawkPlus1.png",
                scale: 0.2,
                anchor: {
                  x: 0,
                  y: 1
                },
                position: {
                  y: -11
                }
              }
            }
          ]
        }
      ]
    });
  });

}).call(this);
